# MehGravity configuration

blocklimit: 8192
# BlockLimit: The max amount of blocks the plugin should search until it thinks it's part of the world. 
# Higher number can cause lag, lower number will ignore largest floating structures.

gravityWorlds:
  - AllWorlds
# If this list contains "AllWorlds", all worlds on your server will be affected by gravity.
# To add your own worlds, use this example:
#gravityWorlds:
#  - WorldName1
#  - WorldName2
#  - OtherWorldsJustContinueLikeThis

# List of supported block names (case-sensitive): http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html

staticBlocks:
   - BEDROCK
#staticBlocks:	(Block materials that won't fall down, any structure connected to these won't fall)
#  - BEDROCK
#  - SPONGE
# And so on..

nonStickyBlocks:
   - BEDROCK
#nonStickyBlocks:	(Block materials that won't stick to any other blocks, just blocks of the same material)
#  - BEDROCK
#  - SPONGE
# And so on..

nonStickyBlocksAgainstEachother:
   - COAL_BLOCK-REDSTONE_BLOCK
#nonStickyBlocksAgainstEachother:	(Block materials that won't stick to specified materials)
#  - BEDROCK-COAL_BLOCK
#  - SPONGE-COBBLESTONE
# And so on..

useMetrics: true
#Should metrics be used?